#!/usr/bin/env bash
# Prints crontab lines for running each source as its own daily instance,
# staggered a few minutes apart so they don't all hit a regulator's servers
# at once. This script only prints — review and add with `crontab -e`
# yourself; it never edits your crontab automatically.
#
# Usage:
#   ./scripts/install_cron.sh /path/to/qara-reg-scraper >> /tmp/qara-reg-scraper-cron.txt
#   crontab -e   # paste the printed lines in

set -euo pipefail

PROJECT_DIR="${1:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"
VENV_BIN="$PROJECT_DIR/.venv/bin"
LOG_DIR="$PROJECT_DIR/logs"

echo "# qara-reg-scraper — one cron entry per source, staggered 5 min apart."
echo "# Generated by scripts/install_cron.sh. Adjust times/paths as needed."
echo "# Add lines for other regulations here as they get implemented (see"
echo "# src/qara_reg_scraper/regulations/__init__.py)."
echo "MAILTO=\"\"   # set to your email to get cron's own failure emails, or leave empty and rely on log files / exit codes"
echo

minute=0
for source in fda:ecfr fda:guidance fda:clearances_510k fda:warning_letters fda:recalls; do
  log_name="${source/:/_}"
  # --no-estimate: skip `run`'s default pre-flight estimate table (an extra
  # listing call) here — nothing's watching an unattended cron run's log
  # for that in real time, and it'd otherwise cost one extra request per
  # source, every day, forever.
  echo "$minute 3 * * * cd $PROJECT_DIR && $VENV_BIN/qara-reg-scraper run --source $source --no-estimate >> $LOG_DIR/$log_name.log 2>&1"
  minute=$((minute + 5))
done

echo
echo "# Optional: rebuild the Postgres index once, after all sources have run"
echo "40 3 * * * cd $PROJECT_DIR && $VENV_BIN/qara-reg-scraper reindex --source all >> $LOG_DIR/reindex.log 2>&1"
